-- 코드를 작성해주세요
SELECT 
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM DEVELOPERS AS D
LEFT JOIN SKILLCODES AS S1 ON S1.NAME = "C#"
LEFT JOIN SKILLCODES AS S2 ON S2.NAME = "Python"
WHERE D.SKILL_CODE & S1.CODE = S1.CODE
OR D.SKILL_CODE & S2.CODE = S2.CODE
ORDER BY ID
;


# SELECT 
#     ID,
#     S.NAME
# FROM DEVELOPERS
# LEFT JOIN SKILLCODES AS S
#     ON S.NAME = "C#" or S.NAME = "Python"
# ;
