SELECT B.yr AS YEAR,
(B.mx - A.SIZE_OF_COLONY) AS YEAR_DEV,
A.ID
FROM ECOLI_DATA AS A
LEFT JOIN
    (SELECT year(B.DIFFERENTIATION_DATE) AS yr, 
     max(B.SIZE_OF_COLONY) AS mx
    FROM ECOLI_DATA AS B
    GROUP BY year(DIFFERENTIATION_DATE)) AS B
ON year(A.DIFFERENTIATION_DATE) = B.yr
ORDER BY YEAR, YEAR_DEV
;
