-- 코드를 작성해주세요
SELECT child.ID AS ID, child.GENOTYPE AS GENOTYPE, parent.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS child
LEFT JOIN ECOLI_DATA AS parent
    ON child.PARENT_ID = parent.ID
WHERE parent.GENOTYPE & child.GENOTYPE >= parent.GENOTYPE
ORDER BY child.ID
;
